### ISSUE TITLE
[Bug]: 手机版本登录用户超过4个时  无法下拉滚动

### ISSUE THREAD

**Issue by ooil929** [heyibear/study_xxqg_download#1]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细项目文档!!!
- [X] 我已经在 [Issue Tracker](https://github.com/heyibear/study_xxqg_download/issues) 和文档中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### studyXxqg 版本

0.1.3

### 运行环境

Linux

### 运行架构

AMD64

### 运行方式

Docker

### 重现步骤

手机版本登录用户超过4个时  无法下拉滚动

### 期望的结果是什么？

超过4个用户 也可以滚动到下面

### 实际的结果是什么？

无法滚动

**Comment by heyibear** [comment]
已经尝试修复，建议更新
