### ISSUE TITLE
[Bug]: 今日已经学习了每周答题，但是查询时还是显示没有学习每周

### ISSUE THREAD

**Issue by ooil929** [heyibear/study_xxqg_download#2]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细项目文档!!!
- [X] 我已经在 [Issue Tracker](https://github.com/heyibear/study_xxqg_download/issues) 和文档中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### studyXxqg 版本

0.1.3

### 运行环境

Linux

### 运行架构

AMD64

### 运行方式

Docker

### 重现步骤

已经学习了39分离包含了5分的每周答题，但是还是显示没有答每周，只是积分显示错误而已
本来还能显示的 ，但是过了几个小时后再刷新查询  就显示今日每周答题没学，但其实已经学了

![image](https://user-images.githubusercontent.com/39184577/229079519-86752cc2-5f4c-42e1-8f9e-7709a409ed54.png)

> 

### 期望的结果是什么？

每周答题能正常显示

### 实际的结果是什么？

有时候每周答题不能显示已完成

**Comment by heyibear** [comment]
已经尝试修复，建议更新
