### ISSUE TITLE
[Bug]: 进入控制面板后不知账号密码

### ISSUE THREAD

**Issue by xuliangwen** [heyibear/study_xxqg_download#3]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细项目文档!!!
- [X] 我已经在 [Issue Tracker](https://github.com/heyibear/study_xxqg_download/issues) 和文档中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### studyXxqg 版本

1.0

### 运行环境

Ubuntu

### 运行架构

None

### 运行方式

Docker

### 重现步骤

进入控制面板后不知账号密码

### 期望的结果是什么？

![图片](https://user-images.githubusercontent.com/129610597/229343713-5213f33e-3254-4a90-900d-2105f6d6923c.png)

### 实际的结果是什么？

账号密码未知

### docker运行命令或者docker-compose的内容

```golang
docker run --name study_xxqg -d -p 8080:8080 -v /etc/study_xxqg/:/opt/config/ heyibear/study_xxqg:latest
```

### 日志记录（可选）

```golang
1
```

### 配置信息（可选）

```yaml
1
```

### 补充说明（可选）

1

**Comment by heyibear** [comment]
默认账号密码都是admin，请确保之前没有拉过别的镜像，如果拉过别人的镜像并且改过密码请输入之前的账号密码，如果没拉过，请确保输入的准确性，建议账号密码都复制粘贴再试试，如果还不行，进入opt/config目录下查看config.yml文件，修改里面的账号和密码

**Comment by xuliangwen** [comment]
好哒 感谢感谢
