### ISSUE TITLE
[Bug]: 学习完后不会停止，并且会导致CPU负载100%

### ISSUE THREAD

**Issue by ooil929** [heyibear/study_xxqg_download#5]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细项目文档!!!
- [X] 我已经在 [Issue Tracker](https://github.com/heyibear/study_xxqg_download/issues) 和文档中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### studyXxqg 版本

0.1.4

### 运行环境

Windows (64)

### 运行架构

None

### 运行方式

Docker

### 重现步骤

多个账号在学习时每周学习完成后还是显示没有每周积分，并且不会停止学习，会死循环的在继续学习  点击停止学习还是会继续学习， 有一些账号会一直在学习 无法停止，并且产生了一些报错 和 CPU负载100%（用原作者的是不会导致CPU100%的）。

![image](https://user-images.githubusercontent.com/39184577/229388881-c4754036-891b-4bf2-9902-d8846f9047ce.png)

### 期望的结果是什么？

1. 学习完成后就算每周积分显示不正常  也能停止学习，避免账号不停学习 导致账号异常
2. CPU不会负载100%异常

### 实际的结果是什么？

1. 学习完成后每周积分显示不正常、 学完后不会自动停止学习
2. CPU负载100%异常

**Comment by heyibear** [comment]
请发送confg.yml全部配置，以便排查错误，涉及到个人信息的配置请删除，以免泄露

**Comment by ooil929** [comment]
# 刷课模式，默认为3，
# 1：只刷文章何视频
# 2：只刷文章和视频和每日答题
# 3：刷文章和视频和每日答题每周答题和专项答题
model: 3

# 日志等级
# panic
# fatal
# error
# warn, warning
# info
# debug
# trace
log_level: "info"

# 是否显示浏览器
show_browser: false

# 跳转学习强国的scheme,默认使用本仓库的action自建scheme,若需自行修改，可直接复制仓库下/docs/scheme.html到任意静态文件服务器
scheme: "http://xxqg.wonzan.com?"


push:
  ding:
    enable: false
    access_token: ""
    secret: ""
# 目前仅支持push-plus推送二维码，默认建议使用push-plus推送
# push-plus使用方法见：http://www.pushplus.plus/
  push_plus:
    enable: false
    token: ""

# telegram交互模式配置
tg:
  enable: false
  chat_id: 0
  token: ""
  # telegram的代理，不配置默认走系统代理
  proxy: ""
  # 自定义tg的api,可通过cloudflare搭建，需自备域名
  custom_api: "https://api.telegram.org"
  # 白名单id,包括群id或者用户id,若为空，则允许所有群所有用户使用，若仅用于单人，直接配置上面的chat_id就可以
  white_list:
    - 123
# 网页端配置
web:
  # 是否启用网页
  enable: true
  #
  host: 0.0.0.0
  port: 8080
  # 网页端登录账号
  account: adddp
  # 网页端登录密码
  password: luoxi
  # web端登录普通用户的账号密码，支持多个用户,普通用户只能看到自己的信息
  common_user:
    # 代表账号为user,密码为123的普通用户，可添加多个，继续在下面写就好了
    hhxx: hhxx
    baise: hhxx

# 微信公众号测试号配置
wechat:
  # 是否启用
  enable: false
  # 开发者平台设置的token
  token: ""
  # 开发者平台的secret
  secret: ""
  # 开发者平台的appId
  app_id: ""
  # 发送登录消息需要使用的消息模板
  # 模板标题，随意  模板内容：  点我登录，然后在浏览器中打开！！
  login_temp_id: ""
  # 发送普通消息需要使用的消息模板
  # 模板标题：随意 模板内容： {{data.DATA}}
  normal_temp_id: ""
  # xxqg会每隔两小时左右检查所有用户的ck有效性，若开启该选项，会在检查失败时推送提醒消息
  push_login_warn: false
  # 微信管理员的openid,可点击关于按钮获得，配置后请重启程序
  super_open_id: ""

# gocq推送配置
qq:
  # 是否启用qq推送
  enable: false
  # gocq的监听地址
  post_addr: "http://127.0.0.1:5700"
  super_user: 123
  access_token: 123
  white_list:
    - 123

# pushDeer推送配置,详情参考psuhDeer官网：http://www.pushdeer.com/official.html
push_deer:
  enable: false
  api: "https://api2.pushdeer.com"
  token: ""

# 登录重试配置
retry:
  # 重试次数
  times: 0

  # 重试之间的时间间隔，单位为分钟
  intervals: 5


# 设置是否定时执行学习程序，格式为cron格式
# "9 19 * * *" 每天19点9分执行一次
# "0 10 * * *” 每天早上十点执行一次
#cron: "0 0 * * *"
cron: "3,31 0,6,14,23 * * *"

# 定时任务随机等待时间，单位：分钟
cron_random_wait: 0

#windows环境自定义浏览器路径，仅支持chromium系列
edge_path: ""

# 启动时等待时间，为了防止代理启动比软件慢而报错，默认不等待，单位秒
start_wait: 0

# 专项答题可接受的最小分值，因一天重复运行的时候，若专项答题未能答满会继续答新的一套题，会浪费题
special_min_score: 1

# 每周答题可接受的最小分值，因一天重复运行的时候，若每周答题未能答满会继续答新的一套题，会浪费题
weekly_min_score: 1

# 题目搜索的顺序，为true则从2018年最开始搜题，否则从现在最新开始搜题
reverse_order: false

# github的代理地址
github_proxy: https://github.com

# 是否开启配置文件热重载 ，在修改配置文件并保存后会自动重启
hot_reload: true

# 自定义消息推送，会在定时任务执行之前推送信息
custom_message: "自定义消息$$$https://www.baidu.com"

# 自定义消息推送定时
custom_cron: ""

pool_size: 1

ji_guang_push:
  enable: false
  secret: ""
  app_key: ""

**Comment by lym0929** [comment]
# 刷课模式，默认为3，
# 1：只刷文章何视频
# 2：只刷文章和视频和每日答题
# 3：刷文章和视频和每日答题每周答题和专项答题
model: 3

# 日志等级
# panic
# fatal
# error
# warn, warning
# info
# debug
# trace
log_level: "info"

# 是否显示浏览器
show_browser: false

# 跳转学习强国的scheme,默认使用本仓库的action自建scheme,若需自行修改，可直接复制仓库下/docs/scheme.html到任意静态文件服务器
scheme: "http://xxqg.wonzan.com?"


push:
  ding:
    enable: false
    access_token: ""
    secret: ""
# 目前仅支持push-plus推送二维码，默认建议使用push-plus推送
# push-plus使用方法见：http://www.pushplus.plus/
  push_plus:
    enable: false
    token: ""

# telegram交互模式配置
tg:
  enable: false
  chat_id: 0
  token: ""
  # telegram的代理，不配置默认走系统代理
  proxy: ""
  # 自定义tg的api,可通过cloudflare搭建，需自备域名
  custom_api: "https://api.telegram.org"
  # 白名单id,包括群id或者用户id,若为空，则允许所有群所有用户使用，若仅用于单人，直接配置上面的chat_id就可以
  white_list:
    - 123
# 网页端配置
web:
  # 是否启用网页
  enable: true
  #
  host: 0.0.0.0
  port: 8080
  # 网页端登录账号
  account: adddp
  # 网页端登录密码
  password: luoxi
  # web端登录普通用户的账号密码，支持多个用户,普通用户只能看到自己的信息
  common_user:
    # 代表账号为user,密码为123的普通用户，可添加多个，继续在下面写就好了
    hhxx: hhxx
    baise: hhxx

# 微信公众号测试号配置
wechat:
  # 是否启用
  enable: false
  # 开发者平台设置的token
  token: ""
  # 开发者平台的secret
  secret: ""
  # 开发者平台的appId
  app_id: ""
  # 发送登录消息需要使用的消息模板
  # 模板标题，随意  模板内容：  点我登录，然后在浏览器中打开！！
  login_temp_id: ""
  # 发送普通消息需要使用的消息模板
  # 模板标题：随意 模板内容： {{data.DATA}}
  normal_temp_id: ""
  # xxqg会每隔两小时左右检查所有用户的ck有效性，若开启该选项，会在检查失败时推送提醒消息
  push_login_warn: false
  # 微信管理员的openid,可点击关于按钮获得，配置后请重启程序
  super_open_id: ""

# gocq推送配置
qq:
  # 是否启用qq推送
  enable: false
  # gocq的监听地址
  post_addr: "http://127.0.0.1:5700"
  super_user: 123
  access_token: 123
  white_list:
    - 123

# pushDeer推送配置,详情参考psuhDeer官网：http://www.pushdeer.com/official.html
push_deer:
  enable: false
  api: "https://api2.pushdeer.com"
  token: ""

# 登录重试配置
retry:
  # 重试次数
  times: 0

  # 重试之间的时间间隔，单位为分钟
  intervals: 5


# 设置是否定时执行学习程序，格式为cron格式
# "9 19 * * *" 每天19点9分执行一次
# "0 10 * * *” 每天早上十点执行一次
#cron: "0 0 * * *"
cron: "3,31 0,2,4,6,7,14,18,23 * * *"

# 定时任务随机等待时间，单位：分钟
cron_random_wait: 0

#windows环境自定义浏览器路径，仅支持chromium系列
edge_path: ""

# 启动时等待时间，为了防止代理启动比软件慢而报错，默认不等待，单位秒
start_wait: 0

# 专项答题可接受的最小分值，因一天重复运行的时候，若专项答题未能答满会继续答新的一套题，会浪费题
special_min_score: 1

# 每周答题可接受的最小分值，因一天重复运行的时候，若每周答题未能答满会继续答新的一套题，会浪费题
weekly_min_score: 1

# 题目搜索的顺序，为true则从2018年最开始搜题，否则从现在最新开始搜题
reverse_order: false

# github的代理地址
github_proxy: https://github.com

# 是否开启配置文件热重载 ，在修改配置文件并保存后会自动重启
hot_reload: true

# 自定义消息推送，会在定时任务执行之前推送信息
custom_message: "自定义消息$$$https://www.baidu.com"

# 自定义消息推送定时
custom_cron: ""

pool_size: 1

ji_guang_push:
  enable: false
  secret: ""
  app_key: ""

**Comment by ooil929** [comment]
![image](https://user-images.githubusercontent.com/39184577/229395190-cb76023d-37b4-4a05-9237-b21923f57280.png)
![image](https://user-images.githubusercontent.com/39184577/229395265-56831f1c-e044-4d90-9f36-4b9b6ee647f2.png)

**Comment by heyibear** [comment]
加我 [Telegram ](https://t.me/heyibear)
