### ISSUE TITLE
[Bug]: docker下还是会出现滑块过不去现象！

### ISSUE THREAD

**Issue by gcl52** [heyibear/study_xxqg_download#8]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细项目文档!!!
- [X] 我已经在 [Issue Tracker](https://github.com/heyibear/study_xxqg_download/issues) 和文档中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### studyXxqg 版本

docker

### 运行环境

Windows (64)

### 运行架构

None

### 运行方式

Docker

### 重现步骤

出现滑块过不去，进入死循环

### 期望的结果是什么？

解决滑块问题

### 实际的结果是什么？

滑块过不去

**Comment by heyibear** [comment]
预计下午推送新版本修复，经过检查是滑的太快导致出现该问题，新版本增加点击刷新重试的功能，暂时的解决方案是多次重新学习
![网络错误](https://img.tucang.cc/api/image/show/afb1ac4cc1b34bc56ca4e158e79a79b8)

**Comment by 1761630764** [comment]
滑块的确  过不去

**Comment by bzlzm** [comment]
我也是，看来是普遍现象了哦

**Comment by twbing** [comment]
win版本也是滑块过不去
